#############################################################################
# Makefile for building: KanColleTool.app/Contents/MacOS/KanColleTool
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  KanColleTool.pro
# Template: app
# Command: /Users/uppfinnarn/Qt/5.2.0/clang_64/bin/qmake -o Makefile KanColleTool.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt/5.2.0/clang_64/mkspecs/macx-clang -I. -I../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../../Qt/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/uppfinnarn/Qt/5.2.0/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/uppfinnarn/Qt/5.2.0/clang_64/lib -framework Carbon -framework QtWidgets -framework QtGui -framework QtCore -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/uppfinnarn/Qt/5.2.0/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		KCMainWindow.cpp \
		KCClient.cpp qrc_resources.cpp \
		moc_KCMainWindow.cpp \
		moc_KCClient.cpp
OBJECTS       = main.o \
		KCMainWindow.o \
		KCClient.o \
		qrc_resources.o \
		moc_KCMainWindow.o \
		moc_KCClient.o
DIST          = ../../../Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		KanColleTool.pro \
		resources.qrc \
		KanColleTool.pro
QMAKE_TARGET  = KanColleTool
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = KanColleTool.app/Contents/MacOS/KanColleTool

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile KanColleTool.app/Contents/PkgInfo KanColleTool.app/Contents/Resources/empty.lproj KanColleTool.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_KCMainWindow.h $(OBJECTS)  
	@test -d KanColleTool.app/Contents/MacOS/ || mkdir -p KanColleTool.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: KanColleTool.pro ../../../Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		KanColleTool.pro \
		resources.qrc \
		/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -o Makefile KanColleTool.pro
../../../Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.2.0/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.2.0/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt/5.2.0/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.2.0/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.2.0/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.2.0/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.2.0/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.2.0/clang_64/mkspecs/features/lex.prf:
KanColleTool.pro:
resources.qrc:
/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/uppfinnarn/Qt/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile KanColleTool.pro

qmake_all: FORCE

KanColleTool.app/Contents/PkgInfo: 
	@test -d KanColleTool.app/Contents || mkdir -p KanColleTool.app/Contents
	@$(DEL_FILE) KanColleTool.app/Contents/PkgInfo
	@echo "APPL????" >KanColleTool.app/Contents/PkgInfo
KanColleTool.app/Contents/Resources/empty.lproj: 
	@test -d KanColleTool.app/Contents/Resources || mkdir -p KanColleTool.app/Contents/Resources
	@touch KanColleTool.app/Contents/Resources/empty.lproj
	
KanColleTool.app/Contents/Info.plist: 
	@test -d KanColleTool.app/Contents || mkdir -p KanColleTool.app/Contents
	@$(DEL_FILE) KanColleTool.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,KanColleTool,g" -e "s,@TYPEINFO@,????,g" Info.plist >KanColleTool.app/Contents/Info.plist
dist: 
	@test -d .tmp/KanColleTool1.0.0 || mkdir -p .tmp/KanColleTool1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/KanColleTool1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/KanColleTool1.0.0/ && $(COPY_FILE) --parents KCMainWindow.h KCClient.h .tmp/KanColleTool1.0.0/ && $(COPY_FILE) --parents main.cpp KCMainWindow.cpp KCClient.cpp .tmp/KanColleTool1.0.0/ && $(COPY_FILE) --parents KCMainWindow.ui .tmp/KanColleTool1.0.0/ && (cd `dirname .tmp/KanColleTool1.0.0` && $(TAR) KanColleTool1.0.0.tar KanColleTool1.0.0 && $(COMPRESS) KanColleTool1.0.0.tar) && $(MOVE) `dirname .tmp/KanColleTool1.0.0`/KanColleTool1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/KanColleTool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r KanColleTool.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		icon.png
	/Users/uppfinnarn/Qt/5.2.0/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_KCMainWindow.cpp moc_KCClient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_KCMainWindow.cpp moc_KCClient.cpp
moc_KCMainWindow.cpp: ../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSystemTrayIcon \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		KCMainWindow.h
	/Users/uppfinnarn/Qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) KCMainWindow.h -o moc_KCMainWindow.cpp

moc_KCClient.cpp: ../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QJsonValue \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qjsonvalue.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrlQuery \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qurlquery.h \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QNetworkRequest \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QNetworkReply \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QNetworkAccessManager \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		KCClient.h
	/Users/uppfinnarn/Qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) KCClient.h -o moc_KCClient.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_KCMainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_KCMainWindow.h
ui_KCMainWindow.h: KCMainWindow.ui
	/Users/uppfinnarn/Qt/5.2.0/clang_64/bin/uic KCMainWindow.ui -o ui_KCMainWindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp KCMainWindow.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSystemTrayIcon \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

KCMainWindow.o: KCMainWindow.cpp KCMainWindow.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSystemTrayIcon \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		ui_KCMainWindow.h \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QInputDialog \
		../../../Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrlQuery \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qurlquery.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KCMainWindow.o KCMainWindow.cpp

KCClient.o: KCClient.cpp KCClient.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QJsonValue \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qjsonvalue.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrlQuery \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qurlquery.h \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QNetworkRequest \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QNetworkReply \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QNetworkAccessManager \
		../../../Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QJsonDocument \
		../../../Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qjsondocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KCClient.o KCClient.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_KCMainWindow.o: moc_KCMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_KCMainWindow.o moc_KCMainWindow.cpp

moc_KCClient.o: moc_KCClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_KCClient.o moc_KCClient.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

