language: cpp
compiler:
  - gcc
  - clang
install: "sudo apt-get install qt5-qmake libqt5webkit5-dev qtdeclarative5-dev libgstreamer-plugins-base0.10-dev libxslt1-dev libgio2.0-cil-dev libgst-dev libglib2.0-dev libxml2-dev libsqlite3-dev"
script: "qmake && make && sudo make install"
